// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: people.proto

package com.ilidan.grpc;

public interface PeopleListOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.ilidan.grpc.PeopleList)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .com.ilidan.grpc.PeopleStreamResponse peopleStreamResponse = 1;</code>
   */
  java.util.List<com.ilidan.grpc.PeopleStreamResponse> 
      getPeopleStreamResponseList();
  /**
   * <code>repeated .com.ilidan.grpc.PeopleStreamResponse peopleStreamResponse = 1;</code>
   */
  com.ilidan.grpc.PeopleStreamResponse getPeopleStreamResponse(int index);
  /**
   * <code>repeated .com.ilidan.grpc.PeopleStreamResponse peopleStreamResponse = 1;</code>
   */
  int getPeopleStreamResponseCount();
  /**
   * <code>repeated .com.ilidan.grpc.PeopleStreamResponse peopleStreamResponse = 1;</code>
   */
  java.util.List<? extends com.ilidan.grpc.PeopleStreamResponseOrBuilder> 
      getPeopleStreamResponseOrBuilderList();
  /**
   * <code>repeated .com.ilidan.grpc.PeopleStreamResponse peopleStreamResponse = 1;</code>
   */
  com.ilidan.grpc.PeopleStreamResponseOrBuilder getPeopleStreamResponseOrBuilder(
      int index);
}
