// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: people.proto

package com.ilidan.grpc;

public interface PeopleRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.ilidan.grpc.PeopleRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string username = 1;</code>
   */
  java.lang.String getUsername();
  /**
   * <code>string username = 1;</code>
   */
  com.google.protobuf.ByteString
      getUsernameBytes();
}
