// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: people.proto

package com.ilidan.grpc;

public interface PeopleStreamRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.ilidan.grpc.PeopleStreamRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 age = 1;</code>
   */
  int getAge();
}
