// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: people.proto

package com.ilidan.grpc;

public interface PeopleResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.ilidan.grpc.PeopleResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string realName = 1;</code>
   */
  java.lang.String getRealName();
  /**
   * <code>string realName = 1;</code>
   */
  com.google.protobuf.ByteString
      getRealNameBytes();
}
