// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: people.proto

package com.ilidan.grpc;

public interface PeopleListOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.ilidan.grpc.PeopleList)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .com.ilidan.grpc.PeopleStreamResponse peopleStreamResponse = 1;</code>
   */
  java.util.List<PeopleStreamResponse>
      getPeopleStreamResponseList();
  /**
   * <code>repeated .com.ilidan.grpc.PeopleStreamResponse peopleStreamResponse = 1;</code>
   */
  PeopleStreamResponse getPeopleStreamResponse(int index);
  /**
   * <code>repeated .com.ilidan.grpc.PeopleStreamResponse peopleStreamResponse = 1;</code>
   */
  int getPeopleStreamResponseCount();
  /**
   * <code>repeated .com.ilidan.grpc.PeopleStreamResponse peopleStreamResponse = 1;</code>
   */
  java.util.List<? extends PeopleStreamResponseOrBuilder>
      getPeopleStreamResponseOrBuilderList();
  /**
   * <code>repeated .com.ilidan.grpc.PeopleStreamResponse peopleStreamResponse = 1;</code>
   */
  PeopleStreamResponseOrBuilder getPeopleStreamResponseOrBuilder(
          int index);
}
