// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: people.proto

package com.ilidan.grpc;

public final class People {
  private People() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_ilidan_grpc_PeopleRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_ilidan_grpc_PeopleRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_ilidan_grpc_PeopleResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_ilidan_grpc_PeopleResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\014people.proto\022\017com.ilidan.grpc\"!\n\rPeopl" +
      "eRequest\022\020\n\010username\030\001 \001(\t\"\"\n\016PeopleResp" +
      "onse\022\020\n\010realName\030\001 \001(\t2k\n\rPeopleService\022" +
      "Z\n\025getRealNameByUsername\022\036.com.ilidan.gr" +
      "pc.PeopleRequest\032\037.com.ilidan.grpc.Peopl" +
      "eResponse\"\000B\033\n\017com.ilidan.grpcB\006PeopleP\001" +
      "b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_ilidan_grpc_PeopleRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_ilidan_grpc_PeopleRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_ilidan_grpc_PeopleRequest_descriptor,
        new String[] { "Username", });
    internal_static_com_ilidan_grpc_PeopleResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_ilidan_grpc_PeopleResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_ilidan_grpc_PeopleResponse_descriptor,
        new String[] { "RealName", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
